### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by darkin1** [api-ai/api-ai-botkit#1]
Hi there,
when I install module and use your example I get error `Cannot find module 'api-ai-botkit'`.
I find out that  you must rename `node_modules/api-ai-botkit/api-ai-botkit.js`  to `node_modules/api-ai-botkit/index.js` and it's work. Can you fix it?

**Comment by xVir** [comment]
Hi, @darkin1 
Sorry, I really missed the issue...

I've fixed it in https://github.com/api-ai/api-ai-botkit/commit/9503f855528a5cfa5394850b0c5df694aa8a18b5
It should work now.

Thanks.
