### ISSUE TITLE
Api AI java client

### ISSUE THREAD

**Issue by shivakrishnaah** [api-ai/api-ai-botkit#2]
There is no Java Client available for API AI. We ended up writing our own java client from available rest services.

**Comment by xVir** [comment]
Hi, @shivakrishnaah 
We have no Java library now. It is still in our plans.
If you want you can use some code from our https://github.com/api-ai/api-ai-android-sdk.

Thanks.

**Comment by xVir** [comment]
Hi, @shivakrishnaah 
Now Java library is available, please take a look https://github.com/api-ai/apiai-java-sdk
Thanks!
